server:
  port: 7000
header:
  cors:
    - 'http://localhost:3000'
    - 'http://127.0.0.1:3000'
database:
  host: localhost
  port: 3306
  username: root
  password: P@ssword1234
  dbname: service-draft
token:
  accessSecret: EFJPzbvVWPJCUrKPjKFagHPhBMBxkbgvwOrTYBHx
  refreshSecret: ovMghrOYCPGFXJocRNwZoAGfKedEjhvaHMVSmqhC
  accessExp: 24
  refreshExp: 30
